# Generated by Django 4.2.6 on 2023-11-07 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='collectionimages',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='collectionimages',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Айди Телеграм-аккаунта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='image',
            name='collection_Images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.collectionimages', verbose_name='Коллекция Изображений'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='master',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business', verbose_name='Бизнесс'),
        ),
        migrations.AlterField(
            model_name='master',
            name='gender',
            field=models.CharField(blank=True, choices=[('MEN', 'Мужчина'), ('WOMEN', 'Женщина')], default='WOMEN', max_length=30, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='master', verbose_name='Изображние'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='master',
            name='surname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='master',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Айди Телеграм-аккаунта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='begin_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'Новый'), ('InProgress', 'В прогрессе'), ('Done', 'Закончено')], max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='service',
            name='master',
            field=models.ManyToManyField(blank=True, null=True, to='api.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное время'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название'),
        ),
    ]
