# Generated by Django 4.2.6 on 2023-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterreview',
            options={'verbose_name': 'Мастер Ревью', 'verbose_name_plural': 'Мастера Ревью'},
        ),
        migrations.AddField(
            model_name='salon',
            name='type',
            field=models.CharField(choices=[('SALON', 'Salon'), ('BEAUTY', 'Beauty')], default=123, max_length=20),
            preserve_default=False,
        ),
    ]
