# Generated by Django 4.2.6 on 2023-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='master',
        ),
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='api.service', verbose_name='Сервис'),
        ),
    ]
