# Generated by Django 4.2.6 on 2023-10-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_masterreview_options_master_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('telegram_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
                ('work_schedule', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('SALON', 'Салон Красоты'), ('BEAUTY', 'Парикмахерская')], max_length=20)),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='master',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='collectionimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='master',
            name='time_begin',
        ),
        migrations.RemoveField(
            model_name='master',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='master',
            name='work_schedule',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master',
            name='booking',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Мужчина'), ('WOMEN', 'Женщина')], default='WOMEN', max_length=30),
        ),
        migrations.DeleteModel(
            name='MasterReview',
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
        migrations.AddField(
            model_name='masteritem',
            name='master_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.master'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
        migrations.AddField(
            model_name='business',
            name='collection_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.collectionimage'),
        ),
        migrations.AddField(
            model_name='business',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.master'),
        ),
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(through='api.MasterItem', to='api.service'),
        ),
    ]
