# Generated by Django 4.2.6 on 2023-11-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_service_master_master_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
