# Generated by Django 4.2.6 on 2023-11-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_business_masteritem_rename_total_price_booking_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Коллекция изображений',
                'verbose_name_plural': 'Коллекция изображений',
            },
        ),
        migrations.RemoveField(
            model_name='masteritem',
            name='master_item',
        ),
        migrations.RemoveField(
            model_name='masteritem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='business',
            name='collection_image',
        ),
        migrations.RemoveField(
            model_name='business',
            name='master',
        ),
        migrations.RemoveField(
            model_name='image',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='master',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='master',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='business',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='master',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master',
            name='business',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='master',
            field=models.ManyToManyField(to='api.master'),
        ),
        migrations.DeleteModel(
            name='CollectionImage',
        ),
        migrations.DeleteModel(
            name='MasterItem',
        ),
        migrations.AddField(
            model_name='collectionimages',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.business'),
        ),
        migrations.AddField(
            model_name='collectionimages',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
