# Generated by Django 4.2.6 on 2023-11-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_collectionimages_remove_masteritem_master_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='int',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='master',
        ),
        migrations.RemoveField(
            model_name='collectionimages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.AddField(
            model_name='collectionimages',
            name='title',
            field=models.CharField(default=123, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='collection_Images',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.collectionimages', verbose_name='Коллекция Изображений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=123, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.business', verbose_name='Бизнесс'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(max_length=30, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booking',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.CharField(max_length=30, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service', verbose_name='Сервис'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='business',
            name='contact_phone',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.BooleanField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='business',
            name='telegram_id',
            field=models.CharField(max_length=30, verbose_name='Айди Телеграм-аккаунта'),
        ),
        migrations.AlterField(
            model_name='business',
            name='time_begin',
            field=models.TimeField(verbose_name='Начальное время'),
        ),
        migrations.AlterField(
            model_name='business',
            name='time_end',
            field=models.TimeField(verbose_name='Конечное время'),
        ),
        migrations.AlterField(
            model_name='business',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('SALON', 'Салон Красоты'), ('BEAUTY', 'Парикмахерская')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='business',
            name='work_schedule',
            field=models.CharField(max_length=30, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='collectionimages',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.business', verbose_name='Бизнесс'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(max_length=30, verbose_name='Айди Телеграм-аккаунта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.IntegerField(verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='master',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business', verbose_name='Бизнесс'),
        ),
        migrations.AlterField(
            model_name='master',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Мужчина'), ('WOMEN', 'Женщина')], default='WOMEN', max_length=30, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображние'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='master',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='master',
            name='telegram_id',
            field=models.CharField(max_length=30, verbose_name='Айди Телеграм-аккаунта'),
        ),
        migrations.AlterField(
            model_name='service',
            name='master',
            field=models.ManyToManyField(to='api.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_time',
            field=models.IntegerField(verbose_name='Минимальное время'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(verbose_name='Дата начала')),
                ('begin_time', models.TimeField(verbose_name='Время начала')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Клиент')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
